const users = [
  {
    name: "Alex Johnson",
    username: "PixelNomad92",
    email: "alex.johnson92@example.com",
    phoneNumber: "555-123-4567",
    street: "123 Elm Street",
    state: "California",
    zip: 90210,
    companyName: "Nomad Ventures",
  },
  {
    name: "Taylor Smith",
    username: "NebulaRiderX",
    email: "taylor.smithx@example.com",
    phoneNumber: "555-987-6543",
    street: "456 Oak Avenue",
    state: "Texas",
    zip: 73301,
    companyName: "Galactic Explorers LLC",
  },
  {
    name: "Jordan Lee",
    username: "FrostByte_47",
    email: "jordan.lee47@example.com",
    phoneNumber: "555-567-8901",
    street: "789 Pine Road",
    state: "New York",
    zip: 10001,
    companyName: "Frozen Systems Inc.",
  },
  {
    name: "Morgan Rivera",
    username: "QuantumKoala",
    email: "morgan.rivera@example.com",
    phoneNumber: "555-345-6789",
    street: "321 Maple Street",
    state: "Florida",
    zip: 33101,
    companyName: "Quantum Innovations",
  },
  {
    name: "Casey Brown",
    username: "ShadowCrafter",
    email: "casey.brown@example.com",
    phoneNumber: "555-234-5678",
    street: "987 Birch Lane",
    state: "Washington",
    zip: 98101,
    companyName: "Crafted Shadows Co.",
  },
  {
    name: "Jamie Patel",
    username: "EchoWolf77",
    email: "jamie.patel77@example.com",
    phoneNumber: "555-678-1234",
    street: "654 Cedar Circle",
    state: "Illinois",
    zip: 60601,
    companyName: "Echo Dynamics",
  },
  {
    name: "Riley Nguyen",
    username: "LunarPhoenix",
    email: "riley.nguyen@example.com",
    phoneNumber: "555-890-2345",
    street: "741 Redwood Drive",
    state: "Oregon",
    zip: 97201,
    companyName: "Phoenix Rising Ltd.",
  },
  {
    name: "Sydney Carter",
    username: "SolarFlare99",
    email: "sydney.carter99@example.com",
    phoneNumber: "555-234-8901",
    street: "963 Aspen Court",
    state: "Nevada",
    zip: 89501,
    companyName: "Solar Solutions",
  },
  {
    name: "Parker Diaz",
    username: "CometChaser",
    email: "parker.diaz@example.com",
    phoneNumber: "555-678-4321",
    street: "852 Spruce Way",
    state: "Colorado",
    zip: 80201,
    companyName: "Comet Enterprises",
  },
  {
    name: "Jordan Bell",
    username: "EcoTrailBlazer",
    email: "jordan.bell@example.com",
    phoneNumber: "555-345-9876",
    street: "369 Cypress Boulevard",
    state: "Arizona",
    zip: 85001,
    companyName: "Trail Blazer Co.",
  },
  {
    name: "Drew Thompson",
    username: "TerraGuardian",
    email: "drew.thompson@example.com",
    phoneNumber: "555-567-6543",
    street: "159 Hemlock Lane",
    state: "Michigan",
    zip: 48101,
    companyName: "TerraTech LLC",
  },
  {
    name: "Avery Lopez",
    username: "NovaAscend",
    email: "avery.lopez@example.com",
    phoneNumber: "555-789-1230",
    street: "753 Alder Avenue",
    state: "Utah",
    zip: 84101,
    companyName: "Nova Innovations",
  },
  {
    name: "Chris Parker",
    username: "GalacticNova",
    email: "chris.parker@example.com",
    phoneNumber: "555-890-5674",
    street: "258 Willow Grove",
    state: "Georgia",
    zip: 30301,
    companyName: "Galactic Systems Inc.",
  },
];

module.exports = { users };
